import { adminSupabase } from "../plugins/supabase.js";
import { streamTaskWithClaude } from "./llm-stream.js";

export async function enqueueRun(runId: string) {
  void execute(runId);
}

async function log(
  runId: string,
  taskId: string,
  level: string,
  message: string,
  payload: Record<string, unknown> = {}
) {
  await adminSupabase.from("task_logs").insert({
    run_id: runId,
    task_id: taskId,
    level,
    message,
    payload,
  });
}

async function execute(runId: string) {
  const { data: run } = await adminSupabase
    .from("agent_runs")
    .select("id, task_id, agent_id, triggered_by_user_id")
    .eq("id", runId)
    .single();

  if (!run) return;

  await adminSupabase
    .from("agent_runs")
    .update({ status: "running", started_at: new Date().toISOString() })
    .eq("id", runId);
  await adminSupabase.from("tasks").update({ status: "ai_working" }).eq("id", run.task_id);

  const { data: task } = await adminSupabase
    .from("tasks")
    .select("id, title, description, metadata")
    .eq("id", run.task_id)
    .single();
  const { data: agent } = await adminSupabase
    .from("agents")
    .select("id, backend, model")
    .eq("id", run.agent_id)
    .single();

  if (!task) return;

  const metadata = task.metadata as { requiresOAuth?: boolean } | null;
  const needsOauth = Boolean(metadata?.requiresOAuth);

  if (needsOauth) {
    await adminSupabase.from("agent_runs").update({ status: "awaiting_input" }).eq("id", runId);
    await adminSupabase.from("tasks").update({ status: "in_review" }).eq("id", run.task_id);
    await log(run.id, run.task_id, "warn", "OAuth approval needed", { provider: "github" });
    return;
  }

  const onLog = (level: string, message: string, payload?: Record<string, unknown>) =>
    log(run.id, run.task_id, level, message, payload ?? {});

  let anthropicApiKey: string | null = null;
  if (run.triggered_by_user_id) {
    const { data: keyRow } = await adminSupabase
      .from("user_settings")
      .select("value")
      .eq("user_id", run.triggered_by_user_id)
      .eq("key", "provider_api_keys")
      .maybeSingle();
    const keys = (keyRow?.value as { anthropic?: string } | null) ?? null;
    anthropicApiKey = (keys?.anthropic && String(keys.anthropic).trim()) || null;
  }

  try {
    if (agent?.backend === "claude") {
      const { fullText } = await streamTaskWithClaude(
        { title: task.title, description: task.description ?? "" },
        { model: agent.model },
        onLog,
        anthropicApiKey
      );

      await adminSupabase.from("task_artifacts").insert({
        task_id: run.task_id,
        run_id: run.id,
        type: "draft",
        title: "Agent draft output",
        url: null,
        metadata: { source: "runner", note: "From model stream", preview: fullText.slice(0, 500) },
      });
    } else {
      await onLog("info", "Non-Claude agent or no agent; no model stream.", { source: "runner" });
      await adminSupabase.from("task_artifacts").insert({
        task_id: run.task_id,
        run_id: run.id,
        type: "draft",
        title: "Agent draft output",
        url: null,
        metadata: { source: "runner", note: "Generated by simulation" },
      });
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await onLog("error", message, { source: "runner", error: String(err) });
    await adminSupabase
      .from("agent_runs")
      .update({
        status: "failed",
        finished_at: new Date().toISOString(),
        error: message,
      })
      .eq("id", runId);
    await adminSupabase.from("tasks").update({ status: "failed" }).eq("id", run.task_id);
    return;
  }

  await adminSupabase
    .from("agent_runs")
    .update({
      status: "completed",
      finished_at: new Date().toISOString(),
      output_snapshot: { result: "ready_for_review" },
    })
    .eq("id", runId);
  await adminSupabase.from("tasks").update({ status: "in_review" }).eq("id", run.task_id);
}
