import { adminSupabase } from "../plugins/supabase.js";

export async function enqueueRun(runId: string) {
  void execute(runId);
}

async function log(runId: string, taskId: string, level: string, message: string, payload: Record<string, unknown> = {}) {
  await adminSupabase.from("task_logs").insert({
    run_id: runId,
    task_id: taskId,
    level,
    message,
    payload
  });
}

async function execute(runId: string) {
  const { data: run } = await adminSupabase
    .from("agent_runs")
    .select("id, task_id, agent_id")
    .eq("id", runId)
    .single();

  if (!run) return;

  await adminSupabase.from("agent_runs").update({ status: "running", started_at: new Date().toISOString() }).eq("id", runId);
  await adminSupabase.from("tasks").update({ status: "ai_working" }).eq("id", run.task_id);

  await log(run.id, run.task_id, "info", "Run started", { tool: "planner" });
  await log(run.id, run.task_id, "info", "Calling tool", { tool: "github.search_issues" });

  const { data: task } = await adminSupabase.from("tasks").select("metadata").eq("id", run.task_id).single();
  const metadata = task?.metadata as { requiresOAuth?: boolean } | null;
  const needsOauth = Boolean(metadata?.requiresOAuth);

  if (needsOauth) {
    await adminSupabase.from("agent_runs").update({ status: "awaiting_input" }).eq("id", runId);
    await adminSupabase.from("tasks").update({ status: "in_review" }).eq("id", run.task_id);
    await log(run.id, run.task_id, "warn", "OAuth approval needed", { provider: "github" });
    return;
  }

  await adminSupabase.from("task_artifacts").insert({
    task_id: run.task_id,
    run_id: run.id,
    type: "draft",
    title: "Agent draft output",
    url: null,
    metadata: { source: "runner", note: "Generated by simulation" }
  });

  await log(run.id, run.task_id, "info", "Run completed and moved to review", { step: "human_review_gate" });

  await adminSupabase
    .from("agent_runs")
    .update({ status: "completed", finished_at: new Date().toISOString(), output_snapshot: { result: "ready_for_review" } })
    .eq("id", runId);

  await adminSupabase.from("tasks").update({ status: "in_review" }).eq("id", run.task_id);
}
